name: Build CI

on:
  push:

jobs:
  # Build the compiler jar file from the submodule
  build-compiler:
    name: Build Compiler
    runs-on: ubuntu-latest
    env:
      COMPILER_NIGHTLY: ${{ github.event_name == 'schedule' }}
      FORCE_COLOR: '1'
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 17
          java-package: jdk
          architecture: x64
      - name: Setup Bazel
        uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: '4.2.2'
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Fetch submodule tags
        working-directory: compiler
        run: git fetch --tags https://github.com/google/closure-compiler.git
      - name: Update compiler submodule to master if nightly build
        if: ${{ env.COMPILER_NIGHTLY == 'true' }}
        working-directory: compiler
        run: |
          git checkout master
          git pull https://github.com/google/closure-compiler.git master
          git log -1 | cat
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Yarn and maven cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ~/.m2/repository
          key: ${{ runner.os }}-yarn-mvn-java11-${{ hashFiles('**/yarn.lock', '**/pom.xml') }}
      - name: Install packages
        run: yarn install --colors=always
      - name: Build jar
        run: ./build-scripts/build_compiler.js
      - name: Tests
        run: node_modules/.bin/mocha --colors
      - name: Upload contrib folder
        uses: actions/upload-artifact@v2
        with:
          name: Contrib folder
          path: compiler/contrib
      - name: Upload compiler jar
        uses: actions/upload-artifact@v2
        with:
          name: Compiler.jar
          path: packages/google-closure-compiler-java/compiler.jar

  # Build the native image on Linux
  build-linux:
    name: Build Linux Native Image
    needs: build-compiler
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '12.x'
      FORCE_COLOR: '1'
      GRAAL_VERSION: '22.0.0.2'
      GRAAL_URL: 'https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.0.0.2/graalvm-ce-java11-linux-amd64-22.0.0.2.tar.gz'
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 17
          java-package: jdk
          architecture: x64
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup upx
        run: |
          UPX_VERSION=3.96
          curl --fail --show-error --location --remote-name "https://github.com/upx/upx/releases/download/v$UPX_VERSION/upx-$UPX_VERSION-amd64_linux.tar.xz"
          tar -xf upx-$UPX_VERSION-amd64_linux.tar.xz
          mv ./upx-$UPX_VERSION-amd64_linux/upx /usr/local/bin/upx
      - name: Download compiler jar
        uses: actions/download-artifact@v2
        with:
          name: Compiler.jar
          path: packages/google-closure-compiler-java/
      - name: Download contrib folder
        uses: actions/download-artifact@v2
        with:
          name: Contrib folder
          path: packages/google-closure-compiler/contrib
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: yarn install --colors=always
      - name: Build image
        working-directory: packages/google-closure-compiler-linux
        run: |
          cp ../google-closure-compiler-java/compiler.jar compiler.jar
          yarn run build
          upx compiler
      - name: Tests
        run: yarn workspaces run test --colors
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Linux image
          path: packages/google-closure-compiler-linux/compiler

  # Build the native image on MacOS
  build-macos:
    name: Build MacOS Native Image
    needs: build-compiler
    runs-on: macos-latest
    env:
      NODE_VERSION: '14.x'
      FORCE_COLOR: '1'
      GRAAL_VERSION: '22.0.0.2'
      GRAAL_URL: 'https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.0.0.2/graalvm-ce-java11-darwin-amd64-22.0.0.2.tar.gz'
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 17
          java-package: jdk
          architecture: x64
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Download compiler jar
        uses: actions/download-artifact@v2
        with:
          name: Compiler.jar
          path: packages/google-closure-compiler-java/
      - name: Download contrib folder
        uses: actions/download-artifact@v2
        with:
          name: Contrib folder
          path: packages/google-closure-compiler/contrib
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: yarn install --colors=always
      - name: Build image
        working-directory: packages/google-closure-compiler-osx
        run: |
          cp ../google-closure-compiler-java/compiler.jar compiler.jar
          yarn run build
      - name: Tests
        run: yarn workspaces run test --colors
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MacOS image
          path: packages/google-closure-compiler-osx/compiler

  # Build the native image on Windows
  build-windows:
    name: Build Windows Native Image
    needs: build-compiler
    runs-on: windows-latest
    env:
      NODE_VERSION: '16.x'
      FORCE_COLOR: '1'
      GRAAL_VERSION: '22.0.0.2'
      GRAAL_URL: 'https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.0.0.2/graalvm-ce-java11-windows-amd64-22.0.0.2.zip'
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 17
          java-package: jdk
          architecture: x64
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Download compiler jar
        uses: actions/download-artifact@v2
        with:
          name: Compiler.jar
          path: packages/google-closure-compiler-java/
      - name: Download contrib folder
        uses: actions/download-artifact@v2
        with:
          name: Contrib folder
          path: packages/google-closure-compiler/contrib
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: yarn install --colors=always
      - name: Build image
        working-directory: packages/google-closure-compiler-windows
        # Enable Visual Studio Build Environment in Powershell
        # See https://stackoverflow.com/a/2124759/1211524
        run: |
          pushd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools"
          cmd /c "VsDevCmd.bat -arch=amd64 & set" |
          foreach {
            if ($_ -match "=") {
              $v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
            }
          }
          popd
          Write-Host "`nVisual Studio 2022 Command Prompt variables set." -ForegroundColor Yellow
          cp ../google-closure-compiler-java/compiler.jar compiler.jar
          yarn run build
      - name: Tests
        shell: cmd
        run: |
          echo "Running Tests"
          yarn workspaces run test --colors
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows image
          path: packages/google-closure-compiler-windows/compiler.exe
